mixin () {
  public query func getApiDoc() : async Text {
    "# AgriScan AI — Backend API\n"
    # "\n"
    # "AgriScan AI is a plant-care assistant for farmers. The backend stores AI-generated\n"
    # "plant-disease scan records, a searchable crops & disease knowledge base, and a\n"
    # "chat history produced by the platform AI assistant. It also exposes the persisted\n"
    # "data through the Caffeine Object Query Layer (OQL) so the Data Intelligence agent\n"
    # "can answer natural-language questions over it.\n"
    # "\n"
    # "## Public methods\n"
    # "\n"
    # "### Identity & authorization\n"
    # "\n"
    # "- `_initialize_access_control() : async ()` — registers the caller. The first\n"
    # "  signed-in (non-anonymous) caller becomes `#admin`; every later signed-in caller\n"
    # "  becomes `#user`. Anonymous callers are ignored. Call this once as a signed-in\n"
    # "  caller before any role-guarded call.\n"
    # "- `getCallerUserRole() : async UserRole` — returns the caller's role\n"
    # "  (`#admin`, `#user`, or `#guest`). Anonymous callers get `#guest`. A signed-in\n"
    # "  caller who has not registered traps with `\"User is not registered\"`.\n"
    # "- `assignCallerUserRole(user : Principal, role : UserRole) : async ()` — assigns a\n"
    # "  role to another principal. Admin-only; a non-admin caller traps with\n"
    # "  `\"Unauthorized: Only admins can assign user roles\"`.\n"
    # "- `isCallerAdmin() : async Bool` — true when the caller is `#admin`. A signed-in\n"
    # "  caller who has not registered traps with `\"User is not registered\"`.\n"
    # "- `_internet_identity_sign_in_start() : async Blob` and\n"
    # "  `_internet_identity_sign_in_finish() : async Result<(), Error>` — Internet\n"
    # "  Identity sign-in handshake used by the frontend. `_finish` also registers the\n"
    # "  caller (first becomes admin).\n"
    # "\n"
    # "### Scan records (AI disease detection)\n"
    # "\n"
    # "- `createScan(input : ScanInput) : async ScanRecord` — sends the uploaded leaf\n"
    # "  image/video reference to the platform AI inference model, which returns a\n"
    # "  structured diagnosis, and saves the completed scan. Requires a registered\n"
    # "  caller (see below).\n"
    # "- `getScan(id : Nat) : async ?ScanRecord` — returns one scan by id, or `null` if\n"
    # "  absent. Requires a registered caller.\n"
    # "- `listScans() : async [ScanRecord]` — returns all scans, newest first (sorted by\n"
    # "  descending `timestamp`). Requires a registered caller.\n"
    # "\n"
    # "### Disease library (public knowledge base)\n"
    # "\n"
    # "- `getDiseases() : async [DiseaseEntry]` — returns every disease entry. Public.\n"
    # "- `getDiseasesByCrop(crop : Text) : async [DiseaseEntry]` — filters entries whose\n"
    # "  `crop` equals the argument. Public.\n"
    # "- `searchDiseases(searchTerm : Text) : async [DiseaseEntry]` — case-insensitive\n"
    # "  substring match against `name`, `crop`, and `symptoms`. Public.\n"
    # "\n"
    # "### AI chat & voice assistant\n"
    # "\n"
    # "- `sendChatMessage(message : Text) : async ChatMessage` — appends the user message\n"
    # "  to the chat history, asks the platform AI assistant, appends the assistant\n"
    # "  reply, and returns the assistant message. Public.\n"
    # "- `getChatHistory() : async [ChatMessage]` — returns the full chat history in\n"
    # "  insertion order. Public.\n"
    # "\n"
    # "### OQL (Caffeine Data Intelligence)\n"
    # "\n"
    # "- `schema() : async Text` — returns the OQL schema describing the queryable\n"
    # "  entities (`scan`, `disease`, `chatMessage`).\n"
    # "- `execute(query : Text) : async Text` — runs a JSON OQL query and returns the\n"
    # "  result rows. Authorization is per entity: `scan` and `chatMessage` are\n"
    # "  controller-only (private), `disease` is public.\n"
    # "\n"
    # "### Object storage\n"
    # "\n"
    # "- `_immutableObjectStorageRefillCashier(refillInformation : ?{ proposed_top_up_amount : ?Nat }) : async { success : ?Bool; topped_up_amount : ?Nat }` — controller/cashier-only refill.\n"
    # "- `_immutableObjectStorageUpdateGatewayPrincipals() : async ()` — refreshes gateway principals.\n"
    # "- `_immutableObjectStorageBlobsAreLive(hashes : [Blob]) : async [Bool]` — reports which blob hashes are live.\n"
    # "- `_immutableObjectStorageBlobsToDelete() : async [Blob]` — lists dead blobs pending deletion (authorized callers only).\n"
    # "- `_immutableObjectStorageConfirmBlobDeletion(blobs : [Blob]) : async ()` — confirms deletion of dead blobs (authorized callers only).\n"
    # "- `_immutableObjectStorageCreateCertificate(blobHash : Text) : async { method : Text; blob_hash : Text }` — returns an upload certificate for a blob hash.\n"
    # "\n"
    # "## Authentication & authorization\n"
    # "\n"
    # "The app uses Internet Identity. A signed-in (non-anonymous) caller is required for\n"
    # "the role-guarded scan endpoints (`createScan`, `getScan`, `listScans`) and for the\n"
    # "authorization endpoints. The disease library, chat, and OQL `disease` entity are\n"
    # "public and callable by anyone, including anonymous callers.\n"
    # "\n"
    # "Registration happens only when a caller signs in through the app's own frontend\n"
    # "(`_initialize_access_control` / `_internet_identity_sign_in_finish`). A principal\n"
    # "that never did so is unregistered even when it belongs to the app's owner, and a\n"
    # "signed-in caller derived against a different origin is a different principal than\n"
    # "the one the frontend registered. An unregistered or anonymous caller on a\n"
    # "role-guarded endpoint receives the following:\n"
    # "\n"
    # "- Anonymous caller: `getUserRole` returns `#guest` (no trap); the scan endpoints\n"
    # "  accept the call.\n"
    # "- Signed-in but unregistered caller: `getUserRole` traps with\n"
    # "  `\"User is not registered\"`.\n"
    # "\n"
    # "The app's frontend pins an Internet Identity derivation origin, published at\n"
    # "`/.well-known/ii-derivation-origin` when available. An agent already holding the\n"
    # "user's Internet Identity authorization derives the correct per-app principal\n"
    # "against that origin (for example `icp identity link web <name> --app <host>`).\n"
    # "Such a delegation acts with the user's full authority in this app until it\n"
    # "expires.\n"
    # "\n"
    # "## Units & encodings\n"
    # "\n"
    # "- `ScanRecord.id` and `ChatMessage.timestamp` / `ScanRecord.timestamp` are `Nat` /\n"
    # "  `Int` nanoseconds since the Unix epoch (`Time.now()`).\n"
    # "- `ScanRecord.confidence` is a `Float` percentage 0–100 parsed from the model's\n"
    # "  integer `CONFIDENCE` field.\n"
    # "- `ScanRecord.severity` is one of `low`, `medium`, or `high` (free text from the\n"
    # "  model).\n"
    # "- `ScanRecord.imageUrl` / `videoUrl` and `DiseaseEntry.imageUrl` are\n"
    # "  `Storage.ExternalBlob` references to object-storage blobs, not inline image\n"
    # "  data. `videoUrl` is optional (`null` when no video was uploaded).\n"
    # "- `ScanRecord.symptoms`, `treatment`, `prevention`, `organicSuggestions` and\n"
    # "  `DiseaseEntry.symptoms`, `causes`, `treatment`, `prevention` are `[Text]`\n"
    # "  arrays.\n"
    # "- `ChatMessage.role` is `#user` or `#assistant`.\n"
    # "- `ScanInput` takes `image : ExternalBlob` and optional `video : ?ExternalBlob`.\n"
    # "\n"
    # "## Lifecycle & polling\n"
    # "\n"
    # "`createScan` and `sendChatMessage` are update calls that make an outbound AI\n"
    # "inference request before returning. They are not idempotent and may take longer\n"
    # "than a typical update; poll by re-calling `getScan(id)` / `getChatHistory()` only\n"
    # "after the call has returned. There is no background job — the result is produced\n"
    # "synchronously within the call.\n"
    # "\n"
    # "## Mutation retry safety\n"
    # "\n"
    # "- `createScan` allocates a fresh id from a monotonic counter and appends a new\n"
    # "  record; retrying creates a duplicate scan with a new id. It is not idempotent.\n"
    # "- `sendChatMessage` appends a user message and an assistant message each call;\n"
    # "  retrying duplicates both messages. It is not idempotent.\n"
    # "- `assignCallerUserRole` is idempotent (assigning the same role again is a no-op).\n"
    # "- `_initialize_access_control` is idempotent for a given caller.\n"
    # "\n"
    # "## Errors, traps & limits\n"
    # "\n"
    # "- `\"User is not registered\"` — a signed-in caller that has not registered calls a\n"
    # "  role-guarded endpoint.\n"
    # "- `\"Unauthorized: Only admins can assign user roles\"` — a non-admin calls\n"
    # "  `assignCallerUserRole`.\n"
    # "- `\"Inference returned no choices\"` / `\"Inference returned no text content\"` —\n"
    # "  the AI inference model returned an empty or malformed response.\n"
    # "- `\"The AI could not identify a disease from this image. Please try a clearer,\n"
    # "  well-lit photo of the affected leaf.\"` — the model returned no usable disease\n"
    # "  name, so `createScan` traps and no blank scan is persisted.\n"
    # "- `\"Unauthorized access\"` — an unauthorized caller invokes an object-storage\n"
    # "  management endpoint.\n"
    # "- OQL `execute` traps on malformed JSON queries; `schema` is always safe to call.\n"
    # "\n"
    # "## Non-obvious gotchas\n"
    # "\n"
    # "- The scan and chat entities are controller-only in OQL, so end users cannot read\n"
    # "  them through `execute`; only the platform agent (acting as controller) can.\n"
    # "  The disease entity is public.\n"
    # "- `listScans` returns scans sorted newest-first; `getChatHistory` returns messages\n"
    # "  in insertion order.\n"
    # "- The AI diagnosis is text-only: the image/video are stored as blob references\n"
    # "  and the model is prompted with a text description; the diagnosis fields are\n"
    # "  parsed from a labeled text response.\n"
    # "- The chat assistant responds in Hinglish (Hindi in Latin script mixed with\n"
    # "  English) when the user writes in Hindi/Hinglish.\n"
  };
};
