/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ScanInput = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'image' : ExternalBlob,
});
export const ScanRecord = IDL.Record({
  'id' : IDL.Nat,
  'treatment' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
  'organicSuggestions' : IDL.Vec(IDL.Text),
  'diseaseName' : IDL.Text,
  'timestamp' : IDL.Int,
  'symptoms' : IDL.Vec(IDL.Text),
  'severity' : IDL.Text,
  'confidence' : IDL.Float64,
  'prevention' : IDL.Vec(IDL.Text),
  'videoUrl' : IDL.Opt(ExternalBlob),
  'expertAdvice' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : ChatRole,
  'timestamp' : IDL.Int,
});
export const DiseaseEntry = IDL.Record({
  'crop' : IDL.Text,
  'name' : IDL.Text,
  'treatment' : IDL.Vec(IDL.Text),
  'imageUrl' : ExternalBlob,
  'symptoms' : IDL.Vec(IDL.Text),
  'causes' : IDL.Vec(IDL.Text),
  'prevention' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createScan' : IDL.Func([ScanInput], [ScanRecord], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDiseases' : IDL.Func([], [IDL.Vec(DiseaseEntry)], ['query']),
  'getDiseasesByCrop' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiseaseEntry)],
      ['query'],
    ),
  'getScan' : IDL.Func([IDL.Nat], [IDL.Opt(ScanRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listScans' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchDiseases' : IDL.Func([IDL.Text], [IDL.Vec(DiseaseEntry)], ['query']),
  'sendChatMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ScanInput = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'image' : ExternalBlob,
  });
  const ScanRecord = IDL.Record({
    'id' : IDL.Nat,
    'treatment' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
    'organicSuggestions' : IDL.Vec(IDL.Text),
    'diseaseName' : IDL.Text,
    'timestamp' : IDL.Int,
    'symptoms' : IDL.Vec(IDL.Text),
    'severity' : IDL.Text,
    'confidence' : IDL.Float64,
    'prevention' : IDL.Vec(IDL.Text),
    'videoUrl' : IDL.Opt(ExternalBlob),
    'expertAdvice' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : ChatRole,
    'timestamp' : IDL.Int,
  });
  const DiseaseEntry = IDL.Record({
    'crop' : IDL.Text,
    'name' : IDL.Text,
    'treatment' : IDL.Vec(IDL.Text),
    'imageUrl' : ExternalBlob,
    'symptoms' : IDL.Vec(IDL.Text),
    'causes' : IDL.Vec(IDL.Text),
    'prevention' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createScan' : IDL.Func([ScanInput], [ScanRecord], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDiseases' : IDL.Func([], [IDL.Vec(DiseaseEntry)], ['query']),
    'getDiseasesByCrop' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiseaseEntry)],
        ['query'],
      ),
    'getScan' : IDL.Func([IDL.Nat], [IDL.Opt(ScanRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listScans' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchDiseases' : IDL.Func([IDL.Text], [IDL.Vec(DiseaseEntry)], ['query']),
    'sendChatMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  });
};

export const init = ({ IDL }) => { return []; };